_src/zeropoint/case/urls.py
from django.urls import path
from . import views

app_name = 'case'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.Indexview.as_view(), name='index'),
    path('case-detail/<int:id>', views.case_detail, name='case_detail')
]

_src/zeropoint/news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.Indexview.as_view(), name='index'),
    path('article-detail/<int:id>', views.article_detail, name='article_detail'),
    path('category/<int:id>', views.Categoryview.as_view(), name='category'),
]

_src/zeropoint/zeropoint/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from .sitemaps import *
# from django.contrib.sitemaps import GenericSitemap
from . import view

sitemaps = {
    'index': IndexSitemap,
    'solution': SoluSitemap,
    'case': CaseSitemap,
    'newsCate': CateSitemap,
    'newsPost': PostSitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('case', include(('case.urls', 'case'), namespace='case')),
    path('solution', include(('solution.urls', 'solution'), namespace='solution')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^$', view.index, name='index'),
    url(r'^product$', view.product, name='product'),
    url(r'^about$', view.about, name='about'),
    url(r'^map.html$', view.map, name='map'),
    url(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps,}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^favicon.ico$',
        RedirectView.as_view(url=r'static/images/favicon.ico')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 'template_name': 'sitemap.html'

_src/zeropoint/news/models.py
from django.db import models
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class Category(models.Model):
    """docstring for ClassName"""
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'
        ordering = ['id']


class Post(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    date = models.DateField()
    image = models.ImageField(upload_to='', null=True)
    abstract = models.TextField(null=True, max_length=200)
    content = RichTextUploadingField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-date']

_src/zeropoint/news/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from .models import *


class Indexview(ListView):
    """docstring for Indexview"""
    model = Post
    template_name = 'news/index.html'
    context_object_name = 'news_list'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        # 首先获得父类生成的传递给模板的字典
        context = super().get_context_data(**kwargs)
        cates = Category.objects.all()
        context['cates'] = cates
        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)
        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        print(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return{}
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range
        if page_number == 1:
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }
        return data


def article_detail(request, id):
    news_list = Post.objects.all()
    curr_article = Post.objects.get(id=id)
    for index, article in enumerate(news_list):
        if len(news_list) != 1:
            if index == 0:
                previous_index = 'None'
                next_index = index + 1
            elif index == len(news_list) - 1:
                previous_index = index - 1
                next_index = index
            else:
                previous_index = index - 1
                next_index = index + 1
        else:
            previous_index = next_index = 'None'
        # 通过id判断当前文章
        if article.id == id:
            curr_article = article
            cate = article.category
            if previous_index == 'None':
                previous_article = None
            else:
                previous_article = news_list[previous_index]
            if next_index == 'None':
                next_article = None
            elif next_index == index:
                next_article = None
            else:
                next_article = news_list[next_index]
            break

    context = {
        'cate': cate,
        'article': curr_article,
        'previous_article': previous_article,
        'next_article': next_article,
    }
    return render(request, 'news/detail.html', context)


class Categoryview(ListView):
    """docstring for Indexview"""
    model = Post
    template_name = 'news/category.html'
    context_object_name = 'news_list'
    paginate_by = 5

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['id'])
        return Post.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cates = Category.objects.all()
        context['category'] = self.category
        context['cates'] = cates
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        print(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return{}
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range
        if page_number == 1:
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }
        return data

_src/zeropoint/templates/news/category.html
<!DOCTYPE html>
<html>
    {% extends 'frame.html' %}
    {% load static %}
    {% block title %}{{ cate.name }}-News-Zeropoint IT{% endblock %}
    {% block description %}{% endblock %}
    <body>
        {% block content %}
        <div class="menuBackground">
            {% include 'nav.html' %}
        </div>     
        <div id="content">
            <div class="tabs">
                <button class="cateChoose2"  onclick="window.location.href = '/news'" > 全部 </button>
                {% for cate in cates %}
                    {% ifequal cate category %}
                    <button class="cateChoose1" onclick="window.location.href = '{{ forloop.counter}} '"> {{cate.name}} </button>
                    {% else %}
                    <button class="cateChoose2" onclick="window.location.href = '{{ forloop.counter}} '"> {{cate.name}} </button>
                    {% endifequal %}
                {% endfor %}
            </div>
        
            {% if news_list %}
                <ul>
                    {% for elem in news_list %}
                        <li>
                            <div class="contentlist">
                                <hr/>
                                <a href="{% url 'news:article_detail' elem.id %} ">
                                    <div class="primary">
                                        <div class="primary">
                                            <h3>{{ elem.title }}</h3>
                                            <p>{{ elem.abstract | slice:":105" }}……</p>
                                        </div>
                                        <div class="second">
                                            <img src="{{ MEDIA_URL }}{{ elem.image }}">
                                        </div>
                                    </div>
                                    <div class="second">
                                        {{ elem.date| date:"m-d Y" }}
                                    </div>
                                </a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="contentlist">暂无新闻</p>
            {% endif %}

            <div class="pagination">
                {% if is_paginated %}
                    {% if first %}
                        <a href="?page=1">1</a>
                    {% endif %}
                    {% if left %}
                        {% if left_has_more %}
                            <span>...</span>
                        {% endif %}
                        {% for i in left %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                    {% endif %}
                    <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
                    {% if right %}
                        {% for i in right %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                        {% if right_has_more %}
                            <span>...</span>
                        {% endif %}
                    {% endif %}
                    {% if last %}
                        <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                    {% endif %}
                {% endif %}              
            </div>
            <br>
        </div>
        {% endblock %}
    </body>
</html>

_src/zeropoint/templates/news/detail.html
<!DOCTYPE html>
<html>
    {% extends 'frame.html' %}
    {% load static %}
    {% block title %}{{ article.title }}-News-Zeropoint IT{% endblock %}
    {% block description %}{{ article.abstract }}{% endblock %}
    <body>
        {% block content %}
        <div class="menuBackground">
            {% include 'nav.html' %}
        </div>
        <div id="content">
            <p style="text-align: left"> <a href="{% url 'news:index' %}" >新闻资讯</a> >> <a href="{% url 'news:category' cate.id %}"> {{cate.name}}</a> >> {{ article.title }}</p>
            <div class="detailtitle" > 
                {{ article.title }}
                <p>{{ article.date | date:"Y-m-d"}}</p>
                <img src="{{ MEDIA_URL }}{{ article.image }}">
            </div>
            <div class="maintext">  {{ article.content | safe}} </div>
            {% if previous_caseArc != next_caseArc %}
                {% if previous_article %}
                    <a class="previous" href="{% url 'news:article_detail' previous_article.id %}">上一篇: {{ previous_article.title }} </a>
                {% else %}
                    <div class="previous">已经是第一篇了</div>
                {% endif %}
                {% if next_article %}
                    <a class="next" href="{% url 'news:article_detail' next_article.id %}">下一篇: {{ next_article.title }} </a>
                {% else %}
                    <div class="next">已经是最后一篇了</div>
                {% endif %}
                <br/>
            {% else %}
                <br/>
            {% endif %}
        </div>        
        {% endblock %}
    </body>
</html>

_src/zeropoint/templates/news/index.html
<!DOCTYPE html>
<html>
    {% extends 'frame.html' %}
    {% load static %}
    {% block title %}News-Zeropoint IT{% endblock %}
    {% block description %}三维电子沙盘新闻资讯。{% endblock %}
    <body>
        {% block content %}
        <div class="menuBackground">
            {% include 'nav.html' %}
        </div>        
        <div id="content">
            <div class="tabs">
                <button class="cateChoose1" onclick="window.location.href = '/news'"> 全部 </button>
                {% for cate in cates %}
                    <button class="cateChoose2" onclick="window.location.href = 'category/{{ forloop.counter}} '"> {{cate.name}} </button>
                {% endfor %}
            </div>

            {% if news_list %}
                <ul>
                    {% for elem in news_list %}
                        <li>                            
                            <div class="contentlist">
                                <hr/>
                                <a href="{% url 'news:article_detail' elem.id %} ">
                                    <div class="primary">
                                        <div class="primary">
                                            <h3>{{ elem.title }}</h3>
                                            <p>{{ elem.abstract | slice:":105" }}……</p>
                                        </div>
                                        <div class="second">
                                            <img src="{{ MEDIA_URL }}{{ elem.image }}">
                                        </div>
                                    </div>
                                    <div class="second">
                                        {{ elem.date| date:"m-d Y" }}
                                    </div>
                                </a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="contentlist">暂无新闻</p>
            {% endif %}
            
            <div class="pagination">
                {% if is_paginated %}
                    {% if first %}
                        <a href="?page=1">1</a>
                    {% endif %}
                    {% if left %}
                        {% if left_has_more %}
                            <span>...</span>
                        {% endif %}
                        {% for i in left %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                    {% endif %}
                    <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
                    {% if right %}
                        {% for i in right %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                        {% if right_has_more %}
                            <span>...</span>
                        {% endif %}
                    {% endif %}
                    {% if last %}
                        <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                    {% endif %}
                {% endif %}              
            </div>
            <br>
        </div>
        {% endblock %}
    </body>
</html>