_src/zeropoint/case/urls.py
from django.urls import path
from . import views

app_name = 'case'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.Indexview.as_view(), name='index'),
    path('case-detail/<int:id>', views.case_detail, name='case_detail')
]

_src/zeropoint/news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.Indexview.as_view(), name='index'),
    path('article-detail/<int:id>', views.article_detail, name='article_detail'),
    path('category/<int:id>', views.Categoryview.as_view(), name='category'),
]

_src/zeropoint/solution/urls.py
from django.urls import path
from . import views

app_name = 'solution'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.Indexview.as_view(), name='index'),
    path('solution-detail/<int:id>', views.solution_detail, name='solution_detail')
]

_src/zeropoint/zeropoint/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from .sitemaps import *
# from django.contrib.sitemaps import GenericSitemap
from . import view

sitemaps = {
    'index': IndexSitemap,
    'solution': SoluSitemap,
    'case': CaseSitemap,
    'newsCate': CateSitemap,
    'newsPost': PostSitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('case', include(('case.urls', 'case'), namespace='case')),
    path('solution', include(('solution.urls', 'solution'), namespace='solution')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^$', view.index, name='index'),
    url(r'^product$', view.product, name='product'),
    url(r'^about$', view.about, name='about'),
    url(r'^map.html$', view.map, name='map'),
    url(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps,}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^favicon.ico$',
        RedirectView.as_view(url=r'static/images/favicon.ico')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 'template_name': 'sitemap.html'

_src/zeropoint/templates/about.html
<!DOCTYPE html>
<html>
    {% extends 'frame.html' %}
    {% load static %}
    {% block title %}About Me-Zeropoint IT{% endblock %}
    {% block description %}关于零点坐标。{% endblock %}
    <body>
        {% block content %}
        <div class="menuBackground">
            {% include 'nav.html' %}
        </div>        
        <div id="content">
            <p class="indexTitle">公司简介</p>
            <p class="maintext">
                苏州零点坐标信息技术有限公司成立于2017年，是国内优秀的无人机应用服务及电子沙盘提供商。我们将多年来在无人机和三维GIS领域积累的丰富经验应用于乡镇级单位，为乡镇管理者提供无人机数据采集、制图建模、平台服务等一整套电子沙盘服务，解决了乡镇工作人手少、数据旧、资料散、无平台等痛点问题，让用户对辖区内各项业务能更轻松地“看全局、抓细节”。我们将持续推动无人机服务市场下沉，为更多用户提供可靠的服务和稳定好用的平台。
            </p>
            <img src="{% static '/images/office.jpg' %}">
            <p class="indexTitle">我们在哪里</p> 
            <iframe src="map.html" width="700" height="450" frameborder="0" scrolling="no"></iframe>
            <br/>
            <p class="indexTitle">发展历程</p>
            <img src="{% static '/images/history.png' %}" class="office">
            <p class="indexTitle">企业文化</p>
            <img src="{% static '/images/culture.png' %}" class="office">
        </div>
        {% endblock %}
    </body>
</html>

_src/zeropoint/templates/frame.html
<head>
        {% load static %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" href="{% static '/styles/main.css' %}">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="{% block description %}{% endblock %}">
</head>
<body>
    {% block content %}{% endblock %}
    <div id="foot">
        <p>Copyright 2020-2022 © 苏州零点坐标信息技术有限公司</p>
        <p>All Rights Reserved   苏ICP备08000108号    <a href="/sitemap.xml" title="Sitemap" target="_blank">网站地图</a></p> 
    </div>
</body>

_src/zeropoint/templates/index.html
<!DOCTYPE html>
<html>
    {% extends 'frame.html' %}
    {% load static %}
    {% block title %}Home-Zeropoint IT{% endblock %}
    {% block description %}我们在美丽的太湖之滨。{% endblock %}
    <body>
        {% block content %}
        <div class="banner">
            <img id="placeholder" src="{% static '/images/hills.jpg' %} " class="banner" />
            {% include 'nav.html' %}
            <div class="bannerItem">
                <a href="{% static '/images/hills.jpg' %}" onmouseover="showPic(this); return false;" onclick="return false;" >·</a></li>
                <a href="{% static '/images/stone.jpg' %}" onmouseover="showPic(this); return false;" onclick="return false;" >·</a></li>
                <a href="{% static '/images/sea.jpg' %}"   onmouseover="showPic(this); return false;" onclick="return false;" >·</a></li>
            </div>            
        </div>
        <div id="content">
            <p class="indexTitle" >解决方案·SOLUTION</p>
            <div class="indexCont1">
                 {% if solution_list %}
                    <ul>
                        {% for elem in solution_list %}
                            <li>
                                <a href="{% url 'solution:solution_detail' elem.id %} ">
                                    <img src="{{ MEDIA_URL }}{{ elem.image }}">
                                    <h2>{{elem.title}}</h2>
                                    <p>{{elem.abstract | slice:":100"}}……</p>
                                </a> 
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>暂无方案</p>
                {% endif %}
                <div class="more" ><a href="/solution" >MORE INFO</a></div>
            </div>

            <p class="indexTitle" >典型案例·CASE</p>
            <div class="indexCont1">
                 {% if case_list %}
                    <ul>
                        {% for elem in case_list %}
                            <li>
                                <a href="{% url 'case:case_detail' elem.id %} ">
                                    <img src="{{ MEDIA_URL }}{{ elem.image }}">
                                    <h2>{{elem.title}}</h2>
                                    <p>{{elem.abstract | slice:":100"}}……</p>
                                </a>                                
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>暂无案例</p>
                {% endif %}
                <div class="more"> <a href="/case" >MORE INFO</a></div>
            </div>

            <p class="indexTitle" >最新资讯·NEWS</p>
            <div class="indexCont1">
                 {% if news_list %}
                    <ul>
                        {% for elem in news_list %}
                            {% if forloop.first %}
                                <div class="indexCont3">
                                    <a href="{% url 'news:article_detail' elem.id %} ">
                                        <img src="{{ MEDIA_URL }}{{ elem.image }}">
                                        <h2>{{ elem.title }}</h2> 
                                    </a>
                                </div>
                            {% else %}
                                <div class="indexCont2">
                                    <a href="{% url 'news:article_detail' elem.id %} ">
                                        {{ elem.title }} <span> {{ elem.date }} </span>
                                    </a>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>暂无新闻</p>
                {% endif %}
                <div class="more"> <a href="/news" >MORE INFO</a></div>
            </div>
            
            <p class="indexTitle" >合作伙伴·PARTNER</p>
            <div class="indexCont4">
                <ul>
                    <li><img src="{% static '/images/logo/01.png' %} "/></li>
                    <li><img src="{% static '/images/logo/02.png' %} "/></li>
                    <li><img src="{% static '/images/logo/03.png' %} "/></li>
                    <li><img src="{% static '/images/logo/04.png' %} "/></li>
                    <li><img src="{% static '/images/logo/05.png' %} "/></li>
                    <li><img src="{% static '/images/logo/06.png' %} "/></li>
                    <li><img src="{% static '/images/logo/07.png' %} "/></li>
                    <li><img src="{% static '/images/logo/08.png' %} "/></li>
                </ul>
            </div>
        </div>        
        <script type="text/javascript"  src="{% static '/scripts/banner.js' %}"></script>
        {% endblock %}
    </body>
</html>

_src/zeropoint/templates/map.html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="百度地图" />
<meta name="description" content="百度地图API自定义地图，帮助用户在可视化操作下生成百度地图" />
<title>百度地图API自定义地图</title>
<!--引用百度地图API-->
<style type="text/css">
    html,body{margin:0;padding:0;}
    .iw_poi_title {color:#0000CD;font-size:14px;font-weight:bold;overflow:hidden;padding-right:13px;white-space:nowrap}
    .iw_poi_content {font:12px arial,sans-serif;overflow:visible;padding-top:4px;white-space:-moz-pre-wrap;word-wrap:break-word}
</style>
<script type="text/javascript" src="http://api.map.baidu.com/api?key=&v=1.1&services=true"></script>
</head>

<body>
  <!--百度地图容器-->
  <div style="width:700px;height:450px;border:#ccc solid 1px;" id="dituContent"></div>
<script type="text/javascript">
    //创建和初始化地图函数：
    function initMap(){
        createMap();//创建地图
        setMapEvent();//设置地图事件
        addMapControl();//向地图添加控件
        addMarker();//向地图中添加marker
    }
    
    //创建地图函数：
    function createMap(){
        var map = new BMap.Map("dituContent");//在百度地图容器中创建一个地图
        var point = new BMap.Point(120.430513,31.344227);//定义一个中心点坐标
        map.centerAndZoom(point,17);//设定地图的中心点和坐标并将地图显示在地图容器中
        window.map = map;//将map变量存储在全局
    }
    
    //地图事件设置函数：
    function setMapEvent(){
        map.enableDragging();//启用地图拖拽事件，默认启用(可不写)
        map.enableScrollWheelZoom();//启用地图滚轮放大缩小
        map.enableDoubleClickZoom();//启用鼠标双击放大，默认启用(可不写)
        map.enableKeyboard();//启用键盘上下左右键移动地图
    }
    
    //地图控件添加函数：
    function addMapControl(){
        //向地图中添加缩放控件
    var ctrl_nav = new BMap.NavigationControl({anchor:BMAP_ANCHOR_TOP_LEFT,type:BMAP_NAVIGATION_CONTROL_LARGE});
    map.addControl(ctrl_nav);
        //向地图中添加缩略图控件
    var ctrl_ove = new BMap.OverviewMapControl({anchor:BMAP_ANCHOR_BOTTOM_RIGHT,isOpen:1});
    map.addControl(ctrl_ove);
        //向地图中添加比例尺控件
    var ctrl_sca = new BMap.ScaleControl({anchor:BMAP_ANCHOR_BOTTOM_LEFT});
    map.addControl(ctrl_sca);
    }
    
    //标注点数组
    var markerArr = [{title:"苏州零点坐标信息技术有限公司",content:"科发路101号503室<br/>电话：18688886666",point:"120.43027|31.344258",isOpen:1,icon:{w:21,h:21,l:0,t:0,x:6,lb:5}}
         ];
    //创建marker
    function addMarker(){
        for(var i=0;i<markerArr.length;i++){
            var json = markerArr[i];
            var p0 = json.point.split("|")[0];
            var p1 = json.point.split("|")[1];
            var point = new BMap.Point(p0,p1);
            var iconImg = createIcon(json.icon);
            var marker = new BMap.Marker(point,{icon:iconImg});
            var iw = createInfoWindow(i);
            var label = new BMap.Label(json.title,{"offset":new BMap.Size(json.icon.lb-json.icon.x+10,-20)});
            marker.setLabel(label);
            map.addOverlay(marker);
            label.setStyle({
                        borderColor:"#808080",
                        color:"#333",
                        cursor:"pointer"
            });
            
            (function(){
                var index = i;
                var _iw = createInfoWindow(i);
                var _marker = marker;
                _marker.addEventListener("click",function(){
                    this.openInfoWindow(_iw);
                });
                _iw.addEventListener("open",function(){
                    _marker.getLabel().hide();
                })
                _iw.addEventListener("close",function(){
                    _marker.getLabel().show();
                })
                label.addEventListener("click",function(){
                    _marker.openInfoWindow(_iw);
                })
                if(!!json.isOpen){
                    label.hide();
                    _marker.openInfoWindow(_iw);
                }
            })()
        }
    }
    //创建InfoWindow
    function createInfoWindow(i){
        var json = markerArr[i];
        var iw = new BMap.InfoWindow("<b class='iw_poi_title' title='" + json.title + "'>" + json.title + "</b><div class='iw_poi_content'>"+json.content+"</div>");
        return iw;
    }
    //创建一个Icon
    function createIcon(json){
        var icon = new BMap.Icon("http://map.baidu.com/image/us_mk_icon.png", new BMap.Size(json.w,json.h),{imageOffset: new BMap.Size(-json.l,-json.t),infoWindowOffset:new BMap.Size(json.lb+5,1),offset:new BMap.Size(json.x,json.h)})
        return icon;
    }
    
    initMap();//创建和初始化地图
</script>

</body>
</html>

_src/zeropoint/templates/nav.html
{% load static %}
<nav>
    <a href="/">
        <img src="{% static '/images/logo.png' %}">
        <p class="comName">零点坐标 </p>
    </a>
    <ul> 
        <li><a href="/">首页</li>  
        <li><a href="/product">产品服务</li> 
        <li><a href="/solution">解决方案</li>
        <li><a href="/case">应用案例</li>
        <li><a href="/news">新闻资讯</li>
        <li><a href="/about">关于我们</li>
    </ul>
</nav>
<div class="tel">
    <img src="{% static '/images/tel.png' %}">186-8888-6666</img>
    <p>工作时间：9:00-17:30</p>
    <a href=""></a>
</div>

_src/zeropoint/templates/product.html
<!DOCTYPE html>
<html>
    {% extends 'frame.html' %}
    {% load static %}
    {% block title %}Product-Zeropoint IT{% endblock %}
    {% block description %}我们的产品是三维电子沙盘。{% endblock %}
    <body>
        {% block content %}
        <div class="menuBackground">
            {% include 'nav.html' %}
        </div>        
        <div id="content"></div>        
        {% endblock %}
    </body>
</html>

_src/zeropoint/templates/sitemap.html
<!DOCTYPE html>
<html>
    {% extends 'frame.html' %}
    {% load static %}
    {% block title %}SiteMap-Zeropoint IT{% endblock %}
    {% block description %}网站地图{% endblock %}
    <body>
        {% block content %}
        <div class="menuBackground">
            {% include 'nav.html' %}
        </div>        
        <div id="content">
            {% include 'sitemap.xml' %}
        </div>        
        {% endblock %}
    </body>
</html>