_src/zeropoint/case/urls.py
from django.urls import path
from . import views

app_name = 'case'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.Indexview.as_view(), name='index'),
    path('case-detail/<int:id>', views.case_detail, name='case_detail')
]

_src/zeropoint/solution/urls.py
from django.urls import path
from . import views

app_name = 'solution'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.Indexview.as_view(), name='index'),
    path('solution-detail/<int:id>', views.solution_detail, name='solution_detail')
]

_src/zeropoint/zeropoint/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from .sitemaps import *
# from django.contrib.sitemaps import GenericSitemap
from . import view

sitemaps = {
    'index': IndexSitemap,
    'solution': SoluSitemap,
    'case': CaseSitemap,
    'newsCate': CateSitemap,
    'newsPost': PostSitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('case', include(('case.urls', 'case'), namespace='case')),
    path('solution', include(('solution.urls', 'solution'), namespace='solution')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^$', view.index, name='index'),
    url(r'^product$', view.product, name='product'),
    url(r'^about$', view.about, name='about'),
    url(r'^map.html$', view.map, name='map'),
    url(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps,}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^favicon.ico$',
        RedirectView.as_view(url=r'static/images/favicon.ico')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 'template_name': 'sitemap.html'

_src/zeropoint/solution/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.


class SoluArcs(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='', null=True)
    abstract = models.TextField(null=True, max_length=200)
    content = RichTextUploadingField()

    def __str__(self):
        return self.title

_src/zeropoint/solution/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView
from .models import SoluArcs


class Indexview(ListView):
    """docstring for Indexview"""
    model = SoluArcs
    template_name = 'solution/index.html'
    context_object_name = 'solution_list'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        # 首先获得父类生成的传递给模板的字典
        context = super().get_context_data(**kwargs)
        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)
        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return{}
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range
        if page_number == 1:
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }
        return data


def solution_detail(request, id):
    solution_list = SoluArcs.objects.all()
    curr_solution = SoluArcs.objects.get(id=id)
    for index, soluArc in enumerate(solution_list):
        if len(solution_list) != 1:
            if index == 0:
                previous_index = 'None'
                next_index = index + 1
            elif index == len(solution_list) - 1:
                previous_index = index - 1
                next_index = index
            else:
                previous_index = index - 1
                next_index = index + 1
        else:
            previous_index = next_index = 'None'
        # 通过id判断当前文章
        if soluArc.id == id:
            curr_solution = soluArc
            if previous_index == 'None':
                previous_soluArc = None
            else:
                previous_soluArc = solution_list[previous_index]
            if next_index == 'None':
                next_soluArc = None
            elif next_index == index:
                next_soluArc = None
            else:
                next_soluArc = solution_list[next_index]
            break

    context = {
        'soluArc': curr_solution,
        'previous_soluArc': previous_soluArc,
        'next_soluArc': next_soluArc,
    }
    return render(request, 'solution/detail.html', context)

_src/zeropoint/templates/solution/detail.html
<!DOCTYPE html>
<html>
    {% extends 'frame.html' %}
    {% load static %}
    {% block title %}{{ soluArc.title }}-Case-Zeropoint IT{% endblock %}
    {% block description %}{{ soluArc.abstract }}{% endblock %}
    <body>
        {% block content %}
        <div class="menuBackground">
            {% include 'nav.html' %}
        </div>
        <div id="content">
            <p style="text-align: left"> <a href="{% url 'solution:index' %}" >解决方案</a> >> {{ soluArc.title }}</p>
            <div class="detailtitle" >
                {{ soluArc.title }}
                <p></p>
                <img src="{{ MEDIA_URL }}{{ soluArc.image }}" >
            </div>            
            <div class="maintext">  {{ soluArc.content | safe}} </div>
            {% if previous_soluArc != next_soluArc %}
                {% if previous_soluArc %}
                    <a class="previous" href="{% url 'solution:solution_detail' previous_soluArc.id %}">上一篇: {{ previous_soluArc.title }} </a>
                {% else %}
                    <div class="previous">已经是第一篇了</div>
                {% endif %}
                {% if next_soluArc %}
                    <a class="next" href="{% url 'solution:solution_detail' next_soluArc.id %}">下一篇: {{ next_soluArc.title }} </a>
                {% else %}
                    <div class="next">已经是最后一篇了</div>
                {% endif %}
                <br/>
            {% else %}
                <br/>
            {% endif %}
        </div>        
        {% endblock %}
    </body>
</html>

_src/zeropoint/templates/solution/index.html
<!DOCTYPE html>
<html>
    {% extends 'frame.html' %}
    {% load static %}
    {% block title %}Solution-Zeropoint IT{% endblock %}
    {% block description %}三维电子沙盘典型解决方案。{% endblock %}
    <body>
        {% block content %}
        <div class="menuBackground">
            {% include 'nav.html' %}
        </div>        
        <div id="content">
            <div class="maintext" style="margin: 3% auto 1%">
                数字农村围绕农民群众最关心最直接最现实的收益问题，建设农村综合管理平台、农村生产监管平台和农村惠农服务平台，加快补齐农村发展和民生短板。农村综合管理平台以乡村治理和精准脱贫为抓手，建设村务管理子系统，支持人口、财务、农资和党务等数据共享；建设精准扶贫子系统，实现扶贫项目管理和资金管理；建设GIS一张图子系统，通过数据可视化直观为领导展示农业领域的各项数据。
            </div>
            
            {% if solution_list %}
                <ul>
                    {% for elem in solution_list %}
                        <li>
                            <div class="contentlist">
                                <a href="{% url 'solution:solution_detail' elem.id %} ">
                                    <p class="indexTitle" >{{ elem.title }}</p>
                                    <div class="mainimg">
                                        <img src="{{ MEDIA_URL }}{{ elem.image }}"> 
                                    </div>                                    
                                    <div class="text">
                                        <p>{{ elem.abstract | slice:":100" }}……</p>
                                    </div>
                                </a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="contentlist">暂无案例</p>
            {% endif %}
        
        
            <div class="pagination">
                {% if is_paginated %}
                    {% if first %}
                        <a href="?page=1">1</a>
                    {% endif %}
                    {% if left %}
                        {% if left_has_more %}
                            <span>...</span>
                        {% endif %}
                        {% for i in left %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                    {% endif %}
                    <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
                    {% if right %}
                        {% for i in right %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                        {% if right_has_more %}
                            <span>...</span>
                        {% endif %}
                    {% endif %}
                    {% if last %}
                        <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                    {% endif %}
                {% endif %}              
            </div>
            <br>
        </div>        
        {% endblock %}
    </body>
</html>